export const flightsOld = [
  {
    departureFrom: {
      city: 'Moscow',
      IATA: 'SVO',
      name: 'Sheremetyevo',
      country: 'Russia',
    },
    departureDate: 'Tue Apr 29 2023 11:00:00 GMT+0200 (Центральная Европа, летнее время)',
    destinationTo: {
      city: 'Стамбул',
      IATA: 'IST',
      name: 'Ataturk',
      country: 'Turkey',
    },
    destinationDate: 'Tue Apr 29 2023 14:00:00 GMT+0200 (Центральная Европа, летнее время)',
    duration: '3h 00m',
    flightNumber: 'FR 2558',
    countPlaces: 200,
    countAvailablePlaces: 75,
    price: 200.25,
  },
  {
    departureFrom: {
      city: 'Moscow',
      IATA: 'SVO',
      name: 'Sheremetyevo',
      country: 'Russia',
    },
    departureDate: 'Tue Apr 30 2023 11:00:00 GMT+0200 (Центральная Европа, летнее время)',
    destinationTo: {
      city: 'Стамбул',
      IATA: 'IST',
      name: 'Ataturk',
      country: 'Turkey',
    },
    destinationDate: 'Tue Apr 30 2023 14:00:00 GMT+0200 (Центральная Европа, летнее время)',
    duration: '3h 00m',
    flightNumber: 'FR 2558',
    countPlaces: 200,
    countAvailablePlaces: 75,
    price: 208.31,
  },
  {
    departureFrom: {
      city: 'Moscow',
      IATA: 'SVO',
      name: 'Sheremetyevo',
      country: 'Russia',
    },
    departureDate: 'Tue Apr 30 2023 11:00:00 GMT+0200 (Центральная Европа, летнее время)',
    destinationTo: {
      city: 'Лондон',
      IATA: 'LCY',
      name: 'London City Airport',
      country: 'Великобритания',
    },
    destinationDate: 'Tue Apr 30 2023 14:00:00 GMT+0200 (Центральная Европа, летнее время)',
    duration: '3h 00m',
    flightNumber: 'FR 2558',
    countPlaces: 200,
    countAvailablePlaces: 75,
    price: 501.89,
  },
];
